version: "3.2"
services:
  postgres-avenger:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-avenger:/var/lib/postgresql/data

volumes:
  postgres-avenger:
